server.port=8088
spring.application.name=empresaMandante
# Configuración de la conexión a Neon
spring.datasource.url=jdbc:postgresql://ep-restless-tree-aqnxqb03-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4rMenqEwPJi2
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Creación bd (Corregido de hiberante a hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true